from enum import Enum

class Season(str, Enum):
    summer = "summer"
    winter = "winter"
    all_season = "all_season"
    spring = "spring"
    fall = "fall"

class Gender(str, Enum):
    male = "male"
    female = "female"

class OutfitPart(str, Enum):
    top = "top"
    bottom = "bottom"
    dress = "dress"
    outerwear = "outerwear"
    shoes = "shoes"
    accessory = "accessory"
    onepiece = "onepiece"

class Formality(str, Enum):
    casual = "casual"
    smart_casual = "smart_casual"
    semi_formal = "semi_formal"
    formal = "formal"
    business_casual = "business_casual"
    sporty = "sporty"

class Category(str, Enum):
    t_shirt = "t_shirt"
    shirt = "shirt"
    polo = "polo"
    sweater = "sweater"
    tank_top = "tank_top"
    hoodie = "hoodie"
    dress = "dress"
    crop_top = "crop_top"
    leggings = "leggings"
    shorts = "shorts"
    skirt = "skirt"
    pants = "pants"
    jeans = "jeans"
    chinos = "chinos"
    jacket = "jacket"
    coat = "coat"
    blazer = "blazer"
    cardigan = "cardigan"
    leather_jacket = "leather_jacket"
    puffer_jacket = "puffer_jacket"
    sneakers = "sneakers"
    boots = "boots"
    sandals = "sandals"
    dress_shoes = "dress_shoes"
    heels = "heels"
    flats = "flats"
    loafers = "loafers"
    hat = "hat"
    scarf = "scarf"
    belt = "belt"
    bag = "bag"
    jewelry = "jewelry"
    watch = "watch"
